/******/ (() => { // webpackBootstrap
/******/ 	"use strict";
var __webpack_exports__ = {};

;// CONCATENATED MODULE: ./src/js/popover.js
class Popover {
  constructor() {}
  showPopover(message, element) {
    const popoverElement = document.createElement("div");
    popoverElement.classList.add("popover");
    popoverElement.innerHTML = `
      <div class="popover-title">
        <p>${message.title}</p>
      </div>
      <div class="popover-text">
        <p>${message.text}</p>
      </div>
    `;
    document.body.appendChild(popoverElement);
    const {
      right,
      top
    } = element.getBoundingClientRect();
    console.log(right);
    popoverElement.style.left = right - element.offsetWidth / 2 - popoverElement.offsetWidth / 2 + "px";
    popoverElement.style.top = top - popoverElement.offsetHeight - 5 + "px";
  }
  toglePopover() {
    const popover = document.querySelector(".popover");
    popover.classList.toggle("hidden");
  }
}
;// CONCATENATED MODULE: ./src/js/app.js

const app_button = document.querySelector(".button");
const message = {
  title: "Any title",
  text: "This text is generated by my mind. As you can see, I have no imagination."
};
const PopoverWidget = new Popover();
const listener = function () {
  PopoverWidget.showPopover(message, app_button);
  app_button.removeEventListener("click", listener);
  app_button.addEventListener("click", () => {
    PopoverWidget.toglePopover();
  });
};
app_button.addEventListener("click", listener);
;// CONCATENATED MODULE: ./src/index.js


/******/ })()
;