import Popover from "./popover";

const button = document.querySelector(".button");
const message = {
  title: "Any title",
  text: "This text is generated by my mind. As you can see, I have no imagination.",
};
const PopoverWidget = new Popover();

const listener = function () {
  PopoverWidget.showPopover(message, button);
  button.removeEventListener("click", listener);
  button.addEventListener("click", () => {
    PopoverWidget.toglePopover();
  });
};

button.addEventListener("click", listener);
