import Popover from "./popover";

const button = document.querySelector('.button');
const message = {
  title: "Any title",
  text: "This text is generated by my mind. As you can see, I have no imagination."
}
const PopoverWidget = new Popover();

button.addEventListener("submit", (event) => {
  debugger
  event.preventDefault();
  PopoverWidget.showPopover(message, button);
})
